### ISSUE TITLE
Kahla 能不能 100% 私有化部署

### ISSUE THREAD

**Issue by dmhai** [AiursoftWeb/Kahla.Obsolete#205]
你好，

Kahla 依靠 Aiursoft Stargate 实现消息推送, 依靠 Aiursoft Probe 存储用户之间发送的图像和文件。

所以，Kahla 没办法做到100% 私有化部署 ?

**Comment by Anduin2017** [comment]
卡拉可以**100%**私有化部署。因为Aiursoft可以100%私有化部署。

请参阅文档： https://wiki.aiursoft.com/Aiursoft%20Infrastructures/About%20Aiursoft%20Infrastructures.md
