### ISSUE TITLE
Handle invalid subscription exception and delete it

### ISSUE THREAD

**Issue by xxyzz** [AiursoftWeb/Kahla.Obsolete#22]
At [here](https://github.com/AiursoftWeb/Kahla/blob/219a40a003aada83cbb7af7ee2ae268e96b21782/Kahla.Server/Services/ThirdPartyPushService.cs#L47).

**Comment by xxyzz** [comment]
Should also delete subscription in [`logoff()`](https://github.com/AiursoftWeb/Kahla/blob/219a40a003aada83cbb7af7ee2ae268e96b21782/Kahla.Server/Controllers/AuthController.cs#L211).

**Comment by Anduin2017** [comment]
How can I get device ID in logoff method? What about this way: when you successfully signed in, I will return you the device ID and you just save it in local storage. When you are trying to signout, pass your devicec ID to my server so that I can delete subscription.

**Comment by xxyzz** [comment]
👌
