### ISSUE TITLE
Supports offset in getMessage API

### ISSUE THREAD

**Issue by xxyzz** [AiursoftWeb/Kahla.Obsolete#29]
Add a parameter `offset` in `getMessage` API, it can be the message id. And  `take` parameter can be negative. For example: `getMessage(10, 12, -15)` will get 15 messages before the message with id 12 in conversation 10. If `offset` is -1, it means the latest message.

**Comment by Anduin2017** [comment]
Hi, @xxyzz. I guess I have successfully fixed it via https://github.com/AiursoftWeb/Kahla/commit/edafcee8e775f7c5f21432c81bda1dae1bc77184.

It seems that I have successfully achieved an API format as `getMesage(ConversationId, SkipMessageId, TakeCount)`. I haven't tested that yet. And the take count must bigger than zero. 

Please try to implement that. If you faced any issue please open it again here! Than you!
