### ISSUE TITLE
Cannot send friend request again.

### ISSUE THREAD

**Issue by ganlvtech** [AiursoftWeb/Kahla.Obsolete#53]
In UserDetail

https://github.com/AiursoftWeb/Kahla/blob/6b436dd15248b3a0940670d3609c55c64de15ad8/Kahla.Server/Controllers/FriendshipController.cs#L320

But in CreateRequest

https://github.com/AiursoftWeb/Kahla/blob/6b436dd15248b3a0940670d3609c55c64de15ad8/Kahla.Server/Controllers/FriendshipController.cs#L121-L124

**Comment by Anduin2017** [comment]
Will resolve.
